AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31

Parameters:
  JumpCloudApiKey:
    Type: String
    NoEcho: true
    AllowedPattern: \b[a-z0-9]{40}\b
  IncrementType:
    Type: String
    Default: day
    AllowedValues:
      - minute
      - minutes
      - hour
      - hours
      - day
      - days
    Description: Allowed values - minute, minutes, hour, hours, day, days.
  IncrementAmount:
    Type: Number
    Default: 1
  OrganizationID:
    Type: String
    Default: ''
    Description: OPTIONAL - This parameter can be used to allow MTP Admins to select which Organization they would like to collect Directory Insights data for.
  Service:
    Type: String
    Default: "all"
    Description: 'Comma-delimited list of desired services to log. Available services: directory,radius,sso,systems,ldap,mdm. Default value is "all"'

Conditions:
  isSingular: !Equals [!Ref "IncrementAmount", 1]

Metadata:
  AWS::ServerlessRepo::Application:
    Name: Xanadu-JC-DirectoryInsights
    Description: This Serverless Application can be used to collect your JumpCloud Directory Insights data at a regular interval.
    Author: Xanadu
    SemanticVersion: 1.0.15

Resources:
  DirectoryInsightsRole:
    Type: AWS::IAM::Role
    Properties:
      Description: A role for use in the JumpCloud Directory Insights Serverless App
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
              - lambda.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AWSLambdaExecute
      Policies:
        - PolicyName: CloudWatchMetrics
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - 'cloudwatch:PutMetricData'
                Resource: '*'
  DirectoryInsightsLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: JumpcloudDirectoryInsightLogs
      RetentionInDays: 1827
  DirectoryInsightsCmk:
    Type: AWS::KMS::Key
    Properties:
      Description: An Symmetric CMK for use in the JumpCloud Directory Insights Serverless App
      KeyPolicy:
        Version: '2012-10-17'
        Id: key-default-1
        Statement:
        - Sid: Enable IAM User Permissions
          Effect: Allow
          Principal:
            AWS: !Sub arn:aws:iam::${AWS::AccountId}:root
          Action: kms:*
          Resource: '*'
        - Sid: Allow use of the key
          Effect: Allow
          Principal:
            AWS: !GetAtt DirectoryInsightsRole.Arn
          Action:
          - kms:DescribeKey
          - kms:Encrypt
          - kms:Decrypt
          - kms:ReEncrypt*
          - kms:GenerateDataKey
          - kms:GenerateDataKeyWithoutPlaintext
          Resource: '*'
  JcApiKey:
    Type: AWS::SecretsManager::Secret
    Properties:
      Description: JumpCloud API Key
      SecretString: !Ref JumpCloudApiKey
  JcApiResourcePolicy:
    Type: AWS::SecretsManager::ResourcePolicy
    Properties:
      SecretId: !Ref JcApiKey
      ResourcePolicy:
        Version: 2012-10-17
        Statement:
        - Effect: Allow
          Principal:
            AWS: !GetAtt DirectoryInsightsRole.Arn
          Action: secretsmanager:GetSecretValue
          Resource: "*"
  DirectoryInsightsFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: get-jcdirectoryinsights.zip
      Handler: get-jcdirectoryinsights.jc_directoryinsights
      MemorySize: 192
      Timeout: 180
      Runtime: python3.9
      Role: !GetAtt DirectoryInsightsRole.Arn
      KmsKeyArn: !GetAtt DirectoryInsightsCmk.Arn
      Environment:
        Variables:
          JcApiKeyArn: !Ref JcApiKey
          incrementType: !Sub ${IncrementType}
          incrementAmount: !Sub ${IncrementAmount}
          service: !Sub ${Service}
          LogGroupName: !Ref DirectoryInsightsLogGroup
          OrgId: !Sub ${OrganizationID}
      Events:
        GrabDirectoryInsights:
          Type: Schedule
          Properties:
            Schedule: !Join ["", [!Sub "rate(${IncrementAmount} ", !If [isSingular, !Select [0, !Split ["s", !Ref "IncrementType"]], !Join ["", [!Select [0, !Split ["s", !Ref "IncrementType"]], "s"]]], ")"]]
